### ISSUE TITLE
'Analytics Usage' for the experiment 'Ebulliometric Determination of Vapour Pressure' is not working

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-chemical-engineering-iitb#2]
'Analytics Usage' for the experiment 'Ebulliometric Determination of Vapour Pressure' is not working

**Comment by mrudhvika940** [comment]
Lab_id and exp_name were not updated, so updated them. And also updated script for analytics usage in "Vapor Liquid Equilibrium" and "Ebulliometric Determination of Vapour Pressure" both experiments.

**Comment by sravanthimodepu** [comment]
Closing the issue.
